import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderLayout from "@/components/Layouts/Header";
import MainArea from "@/components/Layouts/MainArea";

import HeaderComponent from "@/components/HeaderComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className + " bg--400 h-screen"}
        suppressHydrationWarning
      >
        <div className="h-full flex flex-col">
          <HeaderLayout>
            <HeaderComponent />
          </HeaderLayout>
          <MainArea>{children}</MainArea>
          {/* <FooterLayout></FooterLayout> */}
        </div>
      </body>
    </html>
  );
}
